"""empty message

Revision ID: 59c52fbc8d7d
Revises: 1125b8510210
Create Date: 2023-08-14 17:53:52.901928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c52fbc8d7d'
down_revision = '1125b8510210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('itemCode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('itemCode',
               existing_type=sa.String(length=45),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
